// <auto-generated />
namespace Do.Dal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddA_test : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddA_test));
        
        string IMigrationMetadata.Id
        {
            get { return "201604200206055_AddA_test"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
